Register connection
formationSymfony4BrowserGame/BrowserGame pull request #12
Opened 2021-06-16 07:55 UTC by KevinSwp

2021-06-16 15:19 UTC, Bastien-Baloup requested changes
Faudrait peut-être se mettre a jour avec master.

2021-06-16 15:45 UTC, Bastien-Baloup requested changes

2021-06-16 15:45 UTC, Bastien-Baloup commented on app/assets/styles/bulma.scss
> +>>>>>>> master
Le conflit n'est pas géré.

2021-06-16 15:45 UTC, Bastien-Baloup commented on app/assets/styles/styles.scss
> +>>>>>>> master
idem

2021-06-16 15:45 UTC, Bastien-Baloup commented on app/config/routes.yaml
> +#    controller: App\Controller\DefaultController::index
tu peut ajout une nouvelle ligne à la fin du fichier stp ?

2021-06-16 15:45 UTC, Bastien-Baloup commented on app/symfony.lock
> +}
tu peut supprimer ce fichier, il n'est pas utile pour le moment.

2021-06-16 15:45 UTC, Bastien-Baloup commented on app/templates/registration/register.html.twig
> +    {{ form_end(registrationForm) }}
Ton formulaire utilise-t-il les classes de Bulma ?

2021-06-16 15:45 UTC, Bastien-Baloup commented on app/templates/security/index.html.twig
> +{% endblock %}
tu peut supprimer ce fichier.

2021-06-16 15:45 UTC, Bastien-Baloup commented on app/templates/security/login.html.twig
> +    #}
on pourrait activer le remember me, ce ne serait pas une mauvaise idée.

2021-06-16 15:45 UTC, Bastien-Baloup commented on app/translations/security.en.yaml
> +'Invalid credentials.': 'Identifiant ou mot de passe incorrecte'
le fichier ne devrais pas plutôt s'apeller `security.fr.yaml` ?

2021-06-16 15:46 UTC, Bastien-Baloup commented on app/assets/styles/app.css
> +}
PS: Ce fichier n’existe plus dans master.

2021-06-16 16:16 UTC, KevinSwp commented on app/templates/registration/register.html.twig
> +    {{ form_end(registrationForm) }}
Comment ça ? J'essaye d'intégrer Bulma dans twig mais je n'y arrive pas pour l'instant

2021-06-16 17:09 UTC, Bastien-Baloup commented on app/templates/registration/register.html.twig
> +    {{ form_end(registrationForm) }}
Pour intégrer Bulma dans des pages standard, tu peut aller voir ce que Narjes et moi avons fait.
Pour les formulaires je te conseille de créer un thème de formulaire (cf: https://symfony.com/doc/4.4/form/form_themes.html)

2021-06-16 17:16 UTC, Bastien-Baloup commented on app/templates/registration/register.html.twig
> +    {{ form_end(registrationForm) }}
PS: Lit bien la doc et tente de bien la comprendre avant de te lancer dans le code, ça t'éviteras de perdre du temps et de l'énergie dans la correction de bugs.

2021-06-16 18:10 UTC, Bastien-Baloup commented on app/templates/registration/register.html.twig
> +    {{ form_end(registrationForm) }}
PPS: Si après avoir bien lu la doc tu n’arrive pas à comprendre, tu peut demander de l'aide à Nicolas ou Adeline. Ils sont là pour ça.

2021-06-16 18:27 UTC, KevinSwp reviewed
Dans le fichier "app/templates/base.html.twig" il y a un bug aux lignes 64 et 65, il faut effacer les contenus du "href" et re mettre les mêmes contenus pour que les boutons fonctionnent

2021-06-16 20:01 UTC, Bastien-Baloup requested changes

2021-06-16 20:01 UTC, Bastien-Baloup commented on app/assets/styles/bulma.scss
> +@import "~bulma/sass/grid/_all.sass";
ce serait bien une nouvelle ligne à la fin du fichier

2021-06-16 20:01 UTC, Bastien-Baloup commented on app/assets/styles/styles.scss
> +}
idem

2021-06-17 08:16 UTC, Bastien-Baloup approved these changes

2021-06-17 08:17 UTC, NarjesJOMAA approved these changes

2021-06-17 08:18 UTC, merged