Register connection front
formationSymfony4BrowserGame/BrowserGame pull request #14
Opened 2021-06-17 12:34 UTC by KevinSwp

2021-06-17 13:38 UTC, Bastien-Baloup requested changes
L'intégration de Bulma marche pour la connexion mais pas l'inscription : https://i.imgur.com/G1RcOvD.png
Si tu veut ajoute une nouvelle tâche pour que qnn d'autre le fasse plus tard.

2021-06-17 13:38 UTC, Bastien-Baloup commented on app/templates/base.html.twig
> +                                <span class="label">Bienvenue</span> {{ app.user.username }}
La classe `label` est réservée pour les labels de formulaires. La classe `title` serait plus adaptée.

2021-06-17 13:38 UTC, Bastien-Baloup commented on app/templates/security/login.html.twig
> +                        <input class="input" type="text" value="{{ last_username }}" name="mail" id="inputMail" class="form-control" autocomplete="username" required autofocus>
les inputs doivent être dans des elements de classe `control`.
exemple, ici :
```html
<div class="control">
    <input class="input" type="text" value="{{ last_username }}" name="mail" id="inputMail" class="form-control" autocomplete="username" required autofocus>
</div>
```

2021-06-17 13:38 UTC, Bastien-Baloup commented on app/templates/security/login.html.twig
> +                    <input class="input" type="password" name="password" id="inputPassword" class="form-control" autocomplete="current-password" required>
idem

2021-06-17 13:38 UTC, Bastien-Baloup commented on app/templates/security/login.html.twig
> +                    <center><button class="button is-primary mt-5" type="submit">Se connecter</button></center>
idem

2021-06-17 23:39 UTC, Bastien-Baloup requested changes

2021-06-17 23:39 UTC, Bastien-Baloup commented on app/templates/security/login.html.twig
> +                        <input class="input" type="text" value="{{ last_username }}" name="mail" id="inputMail" class="form-control" autocomplete="username" required autofocus>
Ce n'est pas encore réglé, de plus tu as mis deux fois l'attribut class aux inputs

2021-06-18 07:35 UTC, NarjesJOMAA commented on app/templates/security/login.html.twig
>              <div class="columns mt-6">
Le bouton est collé au footer

2021-06-18 09:07 UTC, NarjesJOMAA approved these changes

2021-06-18 20:49 UTC, Bastien-Baloup approved these changes

2021-06-18 21:22 UTC, merged