Compte user
formationSymfony4BrowserGame/BrowserGame pull request #21
Opened 2021-06-28 19:49 UTC by NarjesJOMAA

2021-06-28 20:17 UTC, Bastien-Baloup requested changes

2021-06-28 20:17 UTC, Bastien-Baloup commented on app/assets/scripts/app.js
> +import './modal'
Ceci importe modal.js dans tout les pages du site alors qu'une seule en à besoin.
De plus, modal.js cause une erreur dès que l'on est pas sur la page pour laquelle il à été fait. Cette erreur, à cause de l'endroit ou modal.js est importé, empêche en plus le chargement de feather-icons.

2021-06-29 07:35 UTC, NarjesJOMAA commented on app/assets/scripts/app.js
> +import './modal'
Le problème du chargement des icones est réglé dans les autres pages quand on charge modal.js que dans la page du compte. par contre maintenant on a ce problème de chargement des icones dans la page du compte et de mm pour les pages du jeu!!

2021-06-29 07:45 UTC, Bastien-Baloup commented on app/assets/scripts/app.js
> +import './modal'
Ça c'était un problème du template de base. C'est réglé maintenant.

2021-06-29 07:45 UTC, Bastien-Baloup approved these changes

2021-06-29 07:46 UTC, KevinSwp approved these changes

2021-06-29 07:47 UTC, merged